const catppuccin = require("@catppuccin/palette");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{svelte,js,ts}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "dark",
      "light",
      "aqua",
      "black",
      "dracula",
      "forest",
      "synthwave",
      ...Object.entries(catppuccin.variants).map((v) => ({
        [v[0]]: {
          primary: v[1].sapphire.hex,
          "primary-content": v[1].mantle.hex,
          secondary: v[1].pink.hex,
          accent: v[1].lavender.hex,
          "base-100": v[1].base.hex,
          "base-200": v[1].surface0.hex,
          "base-300": v[1].surface1.hex,
          neutral: v[1].crust.hex,
          "neutral-content": v[1].text.hex,
          success: v[1].green.hex,
          warning: v[1].yellow.hex,
          error: v[1].red.hex,
          "base-content": v[1].text.hex,
        },
      })),
      {
        discord: {
          primary: "#5865f2",
          "primary-content": "#ffffff",
          secondary: "#5865f2",
          "secondary-content": "#ffffff",
          accent: "#4f545c",
          "accent-content": "#ffffff",
          neutral: "#202225",
          "base-100": "#36393f",
          "base-200": "#2f3136",
          "base-300": "#202225",
          success: "#3ba55d",
          "success-content": "#ffffff",
          warning: "#cb8515",
          "warning-content": "#ffffff",
          error: "#ed4245",
          "error-content": "#ffffff",
          "base-content": "#dcddde",
        },
        spotify: {
          primary: "#1ed760",
          "primary-content": "#000000",
          secondary: "#1ed760",
          "secondary-content": "#000000",
          accent: "#535353",
          neutral: "#070707",
          "base-100": "#181818",
          "base-200": "#121212",
          "base-300": "#000000",
          success: "#1ed760",
          warning: "#ffa42b",
          error: "#e91429",
          info: "#0d72ea",
          "base-content": "#ffffff",
        },
        plex: {
          primary: "#e5a00d",
          secondary: "#e5a00d",
          accent: "#545454",
          neutral: "#0c0c0c",
          "base-100": "#575b61",
          "base-200": "#3f4245",
          "base-300": "#282a2d",
          success: "#4db288",
          error: "#f93706",
          info: "#6699ff",
          "base-content": "#ffffff",
        },
      },
    ],
  },
};
