/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{svelte,js,ts}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      "dark",
      "light",
      "aqua",
      "black",
      "dracula",
      "forest",
      "synthwave",
      {
        discord: {
          primary: "#5865f2",
          "primary-content": "#ffffff",
          secondary: "#5865f2",
          "secondary-content": "#ffffff",
          accent: "#4f545c",
          "accent-content": "#ffffff",
          neutral: "#202225",
          "base-100": "#36393f",
          "base-200": "#2f3136",
          "base-300": "#202225",
          success: "#3ba55d",
          "success-content": "#ffffff",
          warning: "#cb8515",
          "warning-content": "#ffffff",
          error: "#ed4245",
          "error-content": "#ffffff",
          "base-content": "#dcddde",
        },
        spotify: {
          primary: "#1ed760",
          "primary-content": "#000000",
          secondary: "#1ed760",
          "secondary-content": "#000000",
          accent: "#535353",
          "base-100": "#181818",
          "base-200": "#121212",
          "base-300": "#000000",
          success: "#1ed760",
          warning: "#ffa42b",
          error: "#e91429",
          info: "#0d72ea",
          "base-content": "#ffffff",
        },
        plex: {
          primary: "#e5a00d",
          secondary: "#e5a00d",
          accent: "#545454",
          "base-100": "#575b61",
          "base-200": "#3f4245",
          "base-300": "#282a2d",
          success: "#4db288",
          error: "#f93706",
          info: "#6699ff",
          "base-content": "#ffffff",
        },
      },
    ],
  },
};
