// Code generated by tygo. DO NOT EDIT.

//////////
// source: api.go

export interface APIErrorResponse {
  err: boolean;
  message?: string;
}
export interface APILoginRequest {
  username: string;
  password: string;
}
export interface APILoginResponse {
  token: string;
}

//////////
// source: struct.go

export interface AccountPermissions {
  owner: boolean;
  artistAdd: boolean;
  artistRemove: boolean;
  songDownload: boolean;
  songRemove: boolean;
}
export interface Account {
  id: string;
  username: string;
  pass: string;
  authToken: string;
  permissions: AccountPermissions;
}
export type MetadataProvider = number /* int */;
export type SoundProvider = number /* int */;
export const MetaProviderSpotify: MetadataProvider = 0;
export const MetaProviderSoundCloud: MetadataProvider = 1;
export const MetaProviderKonami: MetadataProvider = 2;
export const MetaProviderBandLab: MetadataProvider = 3;
export const SoundProviderYouTube: SoundProvider = 0;
export const SoundProviderSoundCloud: SoundProvider = 1;
export type ArtistStatus = number /* int */;
export const ArtistIsAbsent: ArtistStatus = 0;
export const ArtistIsQueued: ArtistStatus = 1;
export const ArtistIsPresent: ArtistStatus = 2;
export interface Artist {
  id: string;
  name: string;
  url: string;
  genres: string[];
  followers: number /* int */;
  icon: string;
  providers: { [key: MetadataProvider]: string};
  status?: ArtistStatus;
}
