// Code generated by tygo. DO NOT EDIT.

//////////
// source: struct.go

export interface AccountPermissions {
  owner: boolean;
  artistAdd: boolean;
  artistRemove: boolean;
  songDownload: boolean;
  songRemove: boolean;
}
export interface Account {
  username: string;
  authToken: string;
  permissions: AccountPermissions;
}
