// Code generated by tygo. DO NOT EDIT.

//////////
// source: queue.go

export type QueueUpdater = any;

//////////
// source: struct.go

export type QueueAction = number /* int */;
export const QALibraryScan: QueueAction = 0;
export const QAArtistAdd: QueueAction = 1;
export const QASongDownload: QueueAction = 2;
export interface QueueItem {
  id: string;
  type: QueueAction;
  data: string;
}
export interface QueuedLibraryScan {
  dir: string;
}
export interface QueuedArtistAdd {
  id: string;
  provider: any /* types.MetadataProvider */;
}
export interface QueuedSongDownload {
  artist: any /* types.Artist */;
  album: any /* types.Album */;
  track: any /* types.Track */;
  provider: any /* types.SoundProvider */;
  url: string;
}
