// Code generated by tygo. DO NOT EDIT.

//////////
// source: downloadable.go

export interface DownloadableAuthor {
  name: string;
  icon: string;
  url: string;
}
export interface Downloadable {
  title: string;
  duration: number /* int */;
  uploadedAt: number /* int */;
  views: number /* int */;
  thumbnail: string;
  author: DownloadableAuthor;
  url: string;
  embed: string;
}

//////////
// source: media.go

export type ArtistStatus = number /* int */;
export type AlbumType = string;
export const ArtistIsAbsent: ArtistStatus = 0;
export const ArtistIsQueued: ArtistStatus = 1;
export const ArtistIsPresent: ArtistStatus = 2;
export const AlbumTypeAlbum: AlbumType = "album";
export const AlbumTypeSingle: AlbumType = "single";
export interface Artist {
  /**
   * Artist
   */
  id: string;
  name: string;
  url: string;
  genres: string[];
  followers: number /* int */;
  icon: string;
  providers: { [key: MetadataProvider]: string };
  status?: ArtistStatus;
  /**
   * Extended Artist
   */
  albums?: Album[];
  /**
   * Metadata
   */
  version?: number /* int */;
}
export interface Album {
  type: AlbumType;
  id: string;
  name: string;
  url: string;
  year: number /* int */;
  image: string;
  tracks: Track[];
  uuid: string;
  provider: MetadataProvider;
}
export interface Track {
  id: string;
  title: string;
  url: string;
  number: number /* int */;
  duration: number /* int */;
  explicit: boolean;
  added?: boolean;
  uuid: string;
}

//////////
// source: meta.go

/**
 * Docs in src/utils.ts
 */
export interface AccountPermissions {
  owner: boolean;
  artistAdd: boolean;
  artistRemove: boolean;
  artistRemoveSelf: boolean;
  songDownload: boolean;
  songRemove: boolean;
  songRemoveSelf: boolean;
}
export interface Account {
  id: string;
  username: string;
  authToken: string;
  permissions: AccountPermissions;
}
export interface Settings {
  libraryFolder: string;
  spotifyID: string;
  spotifySecret: string;
  pipedAPI: string;
}

//////////
// source: providers.go

export type MetadataProvider = string;
export type SoundProvider = string;
export const MetaProviderSpotify: MetadataProvider = "spotify";
export const MetaProviderSoundCloud: MetadataProvider = "soundcloud";
export const MetaProviderKonami: MetadataProvider = "konami";
export const MetaProviderBandLab: MetadataProvider = "bandlab";
export const SoundProviderYouTube: SoundProvider = "youtube";
export const SoundProviderSoundCloud: SoundProvider = "soundcloud";
