// Code generated by tygo. DO NOT EDIT.

//////////
// source: struct.go

export type QueueAction = number /* int */;
export const QALibraryScan: QueueAction = 0;
export interface QueueItem {
  type: QueueAction;
}
