// Code generated by tygo. DO NOT EDIT.

//////////
// source: api.go

export interface APIRequestBase {
  auth: string;
}
export interface APIErrorResponse {
  err: boolean;
  message: string;
}
export interface APILoginRequest {
  username: string;
  password: string;
}

//////////
// source: struct.go

export interface AccountPermissions {
  owner: boolean;
  artistAdd: boolean;
  artistRemove: boolean;
  songDownload: boolean;
  songRemove: boolean;
}
export interface Account {
  id: string;
  username: string;
  pass: string;
  authToken: string;
  permissions: AccountPermissions;
}
