// Code generated by tygo. DO NOT EDIT.

//////////
// source: struct.go

export type QueueAction = number /* int */;
export const QALibraryScan: QueueAction = 0;
export const QAArtistAdd: QueueAction = 1;
export interface QueueItem {
  type: QueueAction;
  data: string;
}
export interface QueuedLibraryScan {
}
export interface QueuedArtistAdd {
  id: string;
  provider: string;
}
